name: Build and Deploy to Cloud Run
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # Your service account key in GitHub secrets

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Install the required beta components for gcloud
      - name: Install beta components for gcloud
        run: |
          gcloud components install beta --quiet

      - name: Deploy to Cloud Run (with build)
        run: |
          gcloud beta run deploy my-app \
            --source . \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory 2Gi \
            --cpu 1 \
            --concurrency 100 \
            --min-instances 0 \
            --max-instances 50 \
            --quiet
